# Generated by Django 4.0.1 on 2022-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskeditor', '0002_richeditor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richeditor',
            name='para',
            field=models.TextField(),
        ),
    ]
